### ISSUE TITLE
where to get salt for randomizing?

### ISSUE THREAD

**Issue by warengonzaga** [ndujaLabs/metashu#12]
I'm curious how to generate salt for re-shuffle, or is it good to leave it without using salt?

**Comment by ThisNate** [comment]
Your salt can be anything you want. Encapsulate any string with spaces in it within double quotes. The point of the salt is that you could replicate the same randomization if you used the same salt string + the same input. If you want to shuffle again and yield different output you'll want to change the salt to something new.

**Comment by warengonzaga** [comment]
> Your salt can be anything you want. Encapsulate any string with spaces in it within double quotes. The point of the salt is that you could replicate the same randomization if you used the same salt string + the same input. If you want to shuffle again and yield different output you'll want to change the salt to something new.

Alright, is there a generator for that?

**Comment by ThisNate** [comment]
> > Your salt can be anything you want. Encapsulate any string with spaces in it within double quotes. The point of the salt is that you could replicate the same randomization if you used the same salt string + the same input. If you want to shuffle again and yield different output you'll want to change the salt to something new.
> 
> Alright, is there a generator for that?

Your keyboard? Any password generator. Literally any string of text you want.

**Comment by warengonzaga** [comment]
> > > Your salt can be anything you want. Encapsulate any string with spaces in it within double quotes. The point of the salt is that you could replicate the same randomization if you used the same salt string + the same input. If you want to shuffle again and yield different output you'll want to change the salt to something new.
> > 
> > 
> > Alright, is there a generator for that?
> 
> Your keyboard? Any password generator. Literally any string of text you want.

Thank you nate for that, now I understand it. Cheers!
